pub mod add_function_routes;
pub mod complete;
pub mod get_loaded_chat_model_name;
pub mod get_loaded_completion_model_name;
pub mod list_chat_models;
pub mod list_completion_models;
pub mod load_chat_model;
pub mod load_completion_model;
pub mod send_chat;
