[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.5.1"
chrono = "0.4.38"
env_logger = "0.11.5"
log = "0.4.22"
paperclip = { version = "0.8.2", features = ["actix4", "actix-files"] }
serde = "1.0.208"
serde_json = "1.0.125"
