# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone", "serde::Serialize", "serde::Deserialize"]


[migrations_directory]
dir = "/home/maurice/maurice/server/migrations"
