// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::DateTime;
use diesel::{Identifiable, Queryable};
use serde::{Serialize, Deserialize};
use crate::schema::*;
use chrono::offset::Utc;
#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize)]
pub struct Content {
    pub id: i32,
    pub type_: String,
    pub text_content: Option<String>,
    pub binary_data: Option<Vec<u8>>,
    pub mime_type: String,
}

#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize)]
#[diesel(primary_key(message_id, content_id))]
pub struct MessageContent {
    pub message_id: i32,
    pub content_id: i32,
}

#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize)]
pub struct Message {
    pub id: i32,
    pub user_id: Option<i32>,
    pub timestamp: DateTime<Utc>,
}

#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize)]
#[diesel(primary_key(user_id, content_id))]
pub struct UserFact {
    pub user_id: i32,
    pub content_id: i32,
}

#[derive(Queryable, Debug, Identifiable, Serialize, Deserialize)]
#[diesel(primary_key(user_id, content_id))]
pub struct UserWakeWordSample {
    pub user_id: i32,
    pub content_id: i32,
}

#[derive(Queryable, Debug, Serialize, Deserialize)]
pub struct User {
    pub id: i32,
    pub name: String,
}

